name: Update Latest Blog Posts CN

on:
  repository_dispatch:
    types: [update-my-profile-cn]

jobs:
  update-readme:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: 14

    - name: Install dependencies
      run: npm install

    - name: Install node-fetch
      run: npm install node-fetch
      
    - name: Install feedparser
      run: npm install feedparser

    - name: Update CNREADME
      run: node update-cn-readme.mjs

    - name: Check if CNREADME has changed
      id: readme-check
      run: |
        git fetch origin master
        changed_files=$(git diff --name-only origin/master)
        if echo "$changed_files" | grep -q 'CNREADME.md'; then
          echo "readme_changed=true" >> $GITHUB_ENV
        else
          echo "readme_changed=false" >> $GITHUB_ENV
        fi

    - name: Commit and push changes
      run: |
        if [[ "${{ env.readme_changed }}" == "true" ]]; then
          git config --local user.name 'github-actions[bot]'
          git config --local user.email 'github-actions[bot]@users.noreply.github.com'
          git add CNREADME.md
          git commit -m "Update CNREADME with latest blog posts"
          git push
        else
          echo "CNREADME.md has not changed. Skipping commit and push."
        fi
